name: MkDocs Build (RationAI Standard)
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    uses: RationAI/.github/.github/workflows/mkdocs-build.yml@main
