name: Pytest (RationAI Standard)
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  run:
    uses: RationAI/.github/.github/workflows/pytest.yml@main
